### ISSUE TITLE
Playtime issues

### ISSUE THREAD

**Issue by Sikatsu** [PlaceholderAPI/Statistics-Expansion#1]
Hey,

I'm using the 1.13 devbuild, however the total playtime placeholder shows incorrect information.
A lot of players have over 60 days which is totally not correct while one of the most active staffmembers has only 4 days..

When I updated the expansion it showed I had 180 days, and a couple of minutes later it said 185 days. So I think it counts days as minutes.

**Comment by ghost** [comment]
Same lol.

**Comment by Sikatsu** [comment]
Also seeing errors on startup.

**Comment by extendedclip** [comment]
Will work on this soon...

**Comment by Sikatsu** [comment]
The errors are gone but the playtime is still incorrect.

**Comment by extendedclip** [comment]
Ya I haven't got to that yet but glad the other errors are fixed. Will work on this later today

**Comment by Sikatsu** [comment]
Thanks!

**Comment by Sikatsu** [comment]
@extendedclip Any time? :P

**Comment by Sikatsu** [comment]
@extendedclip Hey, any time for this issue yet? Would like to fix the playtime placeholders.

**Comment by darbyjack** [comment]
@Sikatsu If you shoot me a DM on Discord (Glare#8499) as a reminder, I'll see if I can fix it by the time I go to bed tonight.

**Comment by Andre601** [comment]
There are several issues/inconveniences I see with the `formatTime` method used in this expansion.

1) Why does it use Duration?
The only value provided is Seconds, so why are you turning seconds into Duration only to turn it back into seconds? Just pass the long directly.

2) What if number is 0 or less?
What would happen if the provided number is 0 or less (-1, -2, ...)
When leaving the duration thing away would the expansion - according to my tests - return an empty String, because the StringBuilder never gets any values added and is therefore empty.
I suggest adding a `if(seconds <= 0)` check and return the seconds together with `s` back in such a case, so 0 would return 0s, -1 would -1s and so on.

3) Why insert?
Why does the StringBuilder use insert?
You could just reverse the order and use a simple append to add the values.
So instead of checking seconds, then minutes, then hours and then days could you reverse the order and use a simple append instead of an insert.
Not sure how this would impact performance and speed but my assumption is, that a append is better than insert because it only has to add the value and not first find the position and put it in between or so.
