### ISSUE TITLE
Placeholder "doesn't" work - Statistics

### ISSUE THREAD

**Issue by WarCook** [PlaceholderAPI/Statistics-Expansion#12]
### Info
Spigot - 1.13
PAPI - the latest
No errors in console

### Issue
Problem with placeholders from expansion statistis (/papi ecloud download Statistic)
don't work. I'm using command above, than /papi reload (even trying reload hole server).
When i'm "checking" placeholder with /papi parse me %statistic_mine_block% it's showing me 0 
(so it should work) but when i'm using command after destroying few block it's still 0. It's happend with all placeholders from statistic. %statistic_deaths% just none work.

### Expected behaviour
Should counting "events"

### Actual behaviour
showing 0 all the time after reloads and manually putting extenstion to folder in PAPI folder.

### How to reproduce
Just commands above

**Comment by totoacee** [comment]
I'm having the same issue, check this: [https://prnt.sc/16ipjb9](https://prnt.sc/16ipjb9)

Dump: [https://paste.helpch.at/xifijovofu](https://paste.helpch.at/xifijovofu)

**Comment by BlitzOffline** [comment]
@totoacee please don't revive 2 years old issues. Anyways. I've noticed this behavior lately and its nothing to do with Statistic expansion. If it parses, it works. The problem is your statistics not being stored. And I've noticed that lately people on purpur can't track the statistics. Also I've noticed that some server software allows you to disable/enable the statistics in their configuration files. So please go check those out and if you can't figure it out yet please go to your server software provider (paper/spigot/airplane/purpur etc.) and ask there.

Thank You
